spring.application.name=backend-server-website

spring.datasource.url=jdbc:postgresql://localhost:5432/Xenon-Dev-DB?characterEncoding=UTF-8&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=Xenon-Dev-Admin
spring.datasource.password=Xenon-Dev64!

logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.security.oauth2=DEBUG
logging.level.org.keycloak=DEBUG
logging.level.org.mockito.session=DEBUG

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

spring.data.rest.detection-strategy=ANNOTATED

allowed.origins=http://localhost:4200, http://127.0.0.1:4200, http://localhost:8080, http://127.0.0.1:8080

keycloak.client-id=xenon-dev-oauth2-client-dev-env-id
keycloak.realm=Xenon-Dev-DEV-ENV
keycloak.uri=http://localhost:8080

spring.data.rest.base-path=/

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/Xenon-Dev-DEV-ENV
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8080/realms/Xenon-Dev-DEV-ENV/protocol/openid-connect/certs

server.port=8443