spring.application.name=backend-server-website

spring.datasource.url=${DEV_MSQL_URL}
spring.datasource.driver-class-name=${DEV_MSQL_DRIVER_CLASS_NAME}
spring.datasource.username=${DEV_MSQL_USERNAME}
spring.datasource.password=${DEV_MSQL_PASSWORD}

logging.level.org.springframework.security=INFO
logging.level.org.springframework.security.oauth2=INFO
logging.level.org.keycloak=INFO

spring.jpa.properties.hibernate.dialect=${DEV_HIBERNATE_DIALECT}
spring.jpa.hibernate.ddl-auto=validate

spring.data.rest.detection-strategy=ANNOTATED

allowed.origins=${DEV_FRONTEND_URL}, ${DEV_KEYCLOAK_URI}

keycloak.client-id=${DEV_KEYCLOAK_CLIENT_ID}
keycloak.realm=${DEV_KEYCLOAK_REALM}
keycloak.uri=${DEV_KEYCLOAK_URI}

spring.data.rest.base-path=${DEV_BASE_PATH}

spring.security.oauth2.resourceserver.jwt.issuer-uri=${DEV_KEYCLOAK_ISSUER_URI}
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${DEV_KEYCLOAK_JWK_SET_URI}
