spring.application.name=backend-server-website

spring.datasource.url=${PROD_MSQL_URL}
spring.datasource.driver-class-name=${PROD_MSQL_DRIVER_CLASS_NAME}
spring.datasource.username=${PROD_MSQL_USERNAME}
spring.datasource.password=${PROD_MSQL_PASSWORD}

logging.level.org.springframework.security=INFO
logging.level.org.springframework.security.oauth2=INFO
logging.level.org.keycloak=INFO

spring.jpa.properties.hibernate.dialect=${PROD_HIBERNATE_DIALECT}
spring.jpa.hibernate.ddl-auto=validate

spring.data.rest.detection-strategy=ANNOTATED

allowed.origins=${PROD_FRONTEND_URL}, ${PROD_KEYCLOAK_URI}

keycloak.client-id=${PROD_KEYCLOAK_CLIENT_ID}
keycloak.realm=${PROD_KEYCLOAK_REALM}
keycloak.uri=${PROD_KEYCLOAK_URI}

spring.data.rest.base-path=${PROD_BASE_PATH}

spring.security.oauth2.resourceserver.jwt.issuer-uri=${PROD_KEYCLOAK_ISSUER_URI}
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${PROD_KEYCLOAK_JWK_SET_URI}