--
-- Custom application tables (Player_ProfileFile and related)
-- This script runs BEFORE Keycloak migrations to set up app-specific schema
-- NOTE: Keycloak will create its own user_entity, realm, role, and other tables
-- so we rename our custom user table to avoid conflicts
--

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: player_profile; Type: TABLE; Schema: public; Owner: Xenon-Dev-Admin
--

CREATE TABLE IF NOT EXISTS public.player_profile (
    player_id bigint NOT NULL PRIMARY KEY,
    losses integer,
    pot integer,
    wins integer
);

ALTER TABLE public.player_profile OWNER TO "Xenon-Dev-Admin";

--
-- Name: player_profile_player_id_seq; Type: SEQUENCE; Schema: public; Owner: Xenon-Dev-Admin
--

ALTER TABLE public.player_profile ALTER COLUMN player_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.player_profile_player_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Use the following commands after Keycloak has generated its tables 
-- (connect with this command: psql -h localhost -p 5432 -d Xenon-Dev-DB -U Xenon-Dev-Admin)
--
/*
ALTER TABLE public.user_entity ADD COLUMN IF NOT EXISTS player_profile_id bigint REFERENCES public.player_profile(player_id);
*/
--
-- Name: accounts_with_player_profiles_view; Type: VIEW; Schema: public; Owner: Xenon-Dev-Admin
--

/*
CREATE OR REPLACE VIEW public.accounts_with_player_profiles_view AS
 SELECT ue.username,
    pp.wins,
    pp.losses,
    pp.pot
   FROM public.user_entity ue
     JOIN public.player_profile pp ON ((ue.player_profile_id = pp.player_id));

ALTER VIEW public.accounts_with_player_profiles_view OWNER TO "Xenon-Dev-Admin";
*/